# Generated by Django 4.1 on 2022-08-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Домен')),
                ('date', models.DateField(verbose_name='Дата окончания')),
                ('draft', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
        ),
    ]
