# Generated by Django 4.1 on 2022-08-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
