# Generated by Django 4.1 on 2022-08-24 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_alter_domainpage_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainpage',
            old_name='date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='domainpage',
            name='now_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
