# Generated by Django 4.1 on 2022-08-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_rename_date_domainpage_create_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainpage',
            options={'verbose_name': 'Домены', 'verbose_name_plural': 'Домены'},
        ),
    ]
