# Generated by Django 4.1 on 2022-08-24 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSLPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Домен')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('now_date', models.DateField(default=datetime.date.today)),
                ('draft', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'SSL',
                'verbose_name_plural': 'SSL',
            },
        ),
    ]
